"""lieux: champs type/address/description

Revision ID: 6fa659535f9b
Revises: 78d7786b2bf6
Create Date: 2026-06-11 19:47:07.510763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa659535f9b'
down_revision: Union[str, Sequence[str], None] = '78d7786b2bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('type', sa.String(length=100), nullable=True))
    op.add_column('places', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('places', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'description')
    op.drop_column('places', 'address')
    op.drop_column('places', 'type')
    # ### end Alembic commands ###
