"""chasse au tresor: hunts, hunt_steps, anonymous_sessions

Revision ID: 76955bf16386
Revises: afbdb774960f
Create Date: 2026-06-08 22:07:37.907238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76955bf16386'
down_revision: Union[str, Sequence[str], None] = 'afbdb774960f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reward_message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id')
    )
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('hunt_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hunt_id'], ['hunts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token', 'hunt_id', name='uq_session_token_hunt')
    )
    op.create_index(op.f('ix_anonymous_sessions_session_token'), 'anonymous_sessions', ['session_token'], unique=False)
    op.create_table('hunt_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunt_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hint', sa.String(length=500), nullable=False),
    sa.Column('validation_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hunt_id'], ['hunts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hunt_id', 'step_order', name='uq_hunt_step_order'),
    sa.UniqueConstraint('hunt_id', 'validation_code', name='uq_hunt_step_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hunt_steps')
    op.drop_index(op.f('ix_anonymous_sessions_session_token'), table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    op.drop_table('hunts')
    # ### end Alembic commands ###
