"""comptes partenaires: backoffice_users.is_active/name, places.owner_id

Revision ID: 78d7786b2bf6
Revises: 76955bf16386
Create Date: 2026-06-11 15:47:03.808686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d7786b2bf6'
down_revision: Union[str, Sequence[str], None] = '76955bf16386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backoffice_users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('backoffice_users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('places', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_places_owner_id', 'places', 'backoffice_users', ['owner_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_places_owner_id', 'places', type_='foreignkey')
    op.drop_column('places', 'owner_id')
    op.drop_column('backoffice_users', 'is_active')
    op.drop_column('backoffice_users', 'name')
    # ### end Alembic commands ###
