"""analytics experience_events scan capture

Revision ID: c57343cda026
Revises: 6fa659535f9b
Create Date: 2026-06-12 15:04:21.519065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57343cda026'
down_revision: Union[str, Sequence[str], None] = '6fa659535f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('scan', 'capture', name='eventtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name='fk_experience_events_experience_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_events_experience_id'), 'experience_events', ['experience_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # drop_table retire la table avec sa FK et son index : sous MySQL on ne peut
    # pas drop l'index seul tant que la clé étrangère s'en sert (donc pas de
    # drop_index séparé ici).
    op.drop_table('experience_events')
